sonar.organization=kagabrielco-netizen
sonar.projectKey=kagabrielco-netizen_laboratorio-adk-ucv
sonar.projectName=laboratorio-adk-ucv

sonar.sources=agente_ucv
sonar.tests=tests
sonar.language=py

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8